additionalProperties:
  formFields:
    - default: 28080
      edit: true
      envKey: PANEL_APP_PORT_HTTP
      labelEn: Web Port
      labelZh: Web 端口
      required: true
      rule: paramPort
      type: number
    - default: "12345678"
      edit: true
      envKey: NEST_ADMIN_PASSWORD
      labelEn: Admin Password
      labelZh: 管理员密码
      required: true
      type: password
    - default: ""
      edit: true
      envKey: NEST_BOT_API_TOKEN
      labelEn: External API Key
      labelZh: 外部 API Key
      required: false
      type: password
    - default: Asia/Shanghai
      edit: true
      envKey: TIME_ZONE
      labelEn: Time Zone
      labelZh: 时区
      required: true
      type: text
